import Head from 'next/head';
import NavBar from '../componets/modules/nav-bar';
import config from 'config';

export default function Home() {
  const { BASE_PATH: basePath } = config;
  console.log('config.BASE_PATH', basePath);
  return (
    <>
      <Head>
        <title>web-card</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={`${basePath}/favicon.ico`} />
      </Head>
      <NavBar />
      <main>
        
      </main>
    </>
  )
}
